name: 'Build and Push to GCP+Octopus'

on:
  push:
    branches:
      - 'main'
      - 'DATA-*'

env:
  PROJECT_ID: 'robpearson-demo' 
  GAR_LOCATION: 'australia-southeast1' 
  REPOSITORY: 'dataeng-container-repo' 
  IMAGE: 'custom-dataflow'

jobs:
  setup-build-publish-deploy:
    name: 'Setup, Build, Publish, and Deploy'
    runs-on: 'ubuntu-latest'
    environment: 'production'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4' 

      # Authenticate DockerHub
      - name: 'Docker Auth'
        uses: 'docker/login-action@v3' 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build the Docker image
      - name: 'Build and push Docker container'
        run: |-
          DOCKER_TAG="${IMAGE}:1.0.${GITHUB_RUN_NUMBER}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "octopussolutionsengineering/robpearson-demo:${DOCKER_TAG}"
